import React from 'react';
import { ArrowRight, ChartNoAxesCombined, ClipboardCheck, UtensilsCrossed } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const monitoringAreas = [
  ['🍲', 'Meal Records', 'Daily meal implementation.'], ['📦', 'Stock', 'Food availability and inventory records.'], ['🧾', 'Purchases', 'Purchase/order records.'], ['👨‍🎓', 'Students', 'Participation-related information.'], ['📊', 'Dashboard', 'Monitoring overview.'], ['🔔', 'Alerts', 'Pending or exceptional records.'],
];
const principles = [['RECORD', 'Capture essential school meal and implementation records digitally.'], ['MONITOR', 'View structured information and identify pending or exceptional records.'], ['ACT', 'Turn operational information into clearer monitoring and timely action.']];
const steps = [['01', 'RECORD', 'School-level information is entered into the platform.'], ['02', 'VERIFY', 'Records can be reviewed before being treated as complete.'], ['03', 'MONITOR', 'Authorised users can monitor implementation information.'], ['04', 'ACT', 'Identified gaps and exceptions can support timely follow-up.']];
const pillars = [['SIMPLE', 'Designed around practical school-level workflows.'], ['CONNECTED', 'Brings operational information into one digital environment.'], ['TRANSPARENT', 'Creates structured digital records for authorised monitoring.'], ['ACTIONABLE', 'Helps users identify pending information and areas requiring attention.']];

export default function Explore() {
  const navigate = useNavigate();
  const enter = () => navigate('/', { state: { loginContext: '' } });
  return <div className="explore-page min-h-screen bg-[#f7faf7] text-slate-800">
    <header className="sticky top-0 z-30 border-b border-[#d9e7dc] bg-[#173b2b]/95 text-white backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><div className="flex items-center gap-3"><img src="/poshanflow-logo.png" alt="PoshanFlow" className="h-10 w-10 rounded-full object-contain" /><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#f5bd6a]">PM POSHAN</p><p className="font-bold">PoshanFlow</p></div></div><button type="button" onClick={enter} className="rounded-md border border-[#f5bd6a]/60 px-3 py-2 text-xs font-bold text-white transition hover:bg-white/10">Enter PoshanFlow</button></div></header>
    <main>
      <section className="overflow-hidden bg-[#173b2b] px-4 py-20 text-white sm:px-6"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-[#f5bd6a]">Digital PM POSHAN monitoring</p><h1 className="text-4xl font-extrabold leading-tight sm:text-6xl">Every Meal Matters.<br />Every Record Counts.</h1><p className="mt-5 text-xl font-semibold leading-relaxed text-[#f5bd6a]">पोषण से सशक्त बचपन।<br />ज्ञान से उज्ज्वल भारत।</p><p className="mt-6 max-w-2xl text-base leading-7 text-white/80">PoshanFlow brings school meal monitoring, operational records and digital insights together in one streamlined platform designed for transparent and efficient PM POSHAN implementation.</p><button type="button" onClick={enter} className="mt-8 inline-flex items-center gap-2 bg-[#e29a36] px-5 py-3 text-sm font-bold text-[#173b2b] transition hover:bg-[#f5bd6a]">Enter PoshanFlow <ArrowRight size={17} /></button></div><div className="relative mx-auto grid w-full max-w-md grid-cols-2 gap-4 rounded-2xl border border-white/15 bg-white/5 p-6 shadow-2xl"><div className="col-span-2 rounded-xl bg-[#285843] p-5 text-center"><UtensilsCrossed className="mx-auto text-[#f5bd6a]" size={35} /><p className="mt-2 font-bold">POSHANFLOW</p><p className="mt-1 text-xs text-white/70">Connected monitoring ecosystem</p></div><div className="rounded-lg bg-white/10 p-4 text-center text-sm">Meal Monitoring</div><div className="rounded-lg bg-white/10 p-4 text-center text-sm">School Tracking</div><div className="rounded-lg bg-white/10 p-4 text-center text-sm">Stock & Purchases</div><div className="rounded-lg bg-white/10 p-4 text-center text-sm">Insights & Reports</div></div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6"><p className="section-kicker">What is PoshanFlow?</p><h2 className="section-title">One Platform. Every Meal. Better Monitoring.</h2><p className="section-copy">PoshanFlow is a digital monitoring portal designed to organise and connect school-level information related to PM POSHAN implementation, helping authorised users record, track and review essential operational data.</p><div className="mt-10 grid gap-5 md:grid-cols-3">{principles.map(([title, text], index) => <article key={title} className="explore-card"><div className="mb-4 text-[#e29a36]">{index === 0 ? <ClipboardCheck /> : index === 1 ? <ChartNoAxesCombined /> : <ArrowRight />}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="bg-[#edf5ef] px-4 py-20 sm:px-6"><div className="mx-auto max-w-5xl text-center"><p className="section-kicker">What PoshanFlow connects</p><h2 className="section-title">One connected view of implementation</h2><div className="mx-auto mt-10 grid max-w-3xl items-center gap-4 sm:grid-cols-3"><div className="ecosystem-node">Students</div><div className="hidden sm:block">↓</div><div className="ecosystem-node">Meals</div><div className="ecosystem-node">Stock</div><div className="rounded-full bg-[#173b2b] px-6 py-8 font-extrabold tracking-wide text-white shadow-xl">POSHANFLOW</div><div className="ecosystem-node">Purchases</div><div className="ecosystem-node">Monitoring</div><div className="hidden sm:block">↑</div><div className="ecosystem-node">Reports</div></div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6"><p className="section-kicker">How PoshanFlow works</p><h2 className="section-title">From entry to follow-up</h2><div className="mt-10 grid gap-4 md:grid-cols-4">{steps.map(([number, title, text]) => <article key={title} className="explore-step"><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="mt-8 text-center text-sm font-bold tracking-wide text-[#285843]">RECORD <ArrowRight className="inline" size={15} /> VERIFY <ArrowRight className="inline" size={15} /> MONITOR <ArrowRight className="inline" size={15} /> ACT</p></section>
      <section className="bg-white px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><p className="section-kicker">Key monitoring areas</p><h2 className="section-title">Information that supports better monitoring</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{monitoringAreas.map(([icon, title, text]) => <button type="button" key={title} onClick={enter} className="explore-area text-left"><span>{icon}</span><div><h3>{title}</h3><p>{text}</p></div></button>)}</div><p className="mt-5 text-xs text-slate-500">These areas are available to authorised users after sign-in.</p></div></section>
      <section className="bg-[#edf5ef] px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><p className="section-kicker">Why PoshanFlow?</p><h2 className="section-title">From Data to Better Visibility</h2><div className="mt-10 grid gap-5 md:grid-cols-4">{pillars.map(([title, text]) => <article key={title} className="explore-card"><h3>{title}</h3><p>{text}</p></article>)}</div><div className="mx-auto mt-12 max-w-sm rounded-xl border border-[#bad1bf] bg-white p-6 text-center text-sm font-bold leading-8 text-[#285843]">School Records<br />↓<br />Structured Data<br />↓<br />Digital Monitoring<br />↓<br />Clearer Visibility<br />↓<br />Timely Action</div></div></section>
      <section className="bg-[#173b2b] px-4 py-20 text-center text-white sm:px-6"><h2 className="mx-auto max-w-3xl text-3xl font-extrabold sm:text-4xl">Better Monitoring. Better Nutrition. Better Futures.</h2><p className="mx-auto mt-5 max-w-2xl leading-7 text-white/80">PoshanFlow connects everyday school-level records with digital monitoring to make information easier to capture, understand and act upon.</p><button type="button" onClick={enter} className="mt-8 inline-flex items-center gap-2 bg-[#e29a36] px-5 py-3 text-sm font-bold text-[#173b2b] hover:bg-[#f5bd6a]">Enter PoshanFlow <ArrowRight size={17} /></button></section>
    </main>
  </div>;
}
